/*global systemDictionary:true */
'use strict';

systemDictionary = {
    'Connection Device': {
        'en': 'Connection Device',
        'de': 'Verbindungsgerät',
        'ru': 'Устройство подключения',
        'pt': 'Dispositivo de conexão',
        'nl': 'Verbindingsapparaat',
        'fr': 'Dispositif de connexion',
        'it': 'Dispositivo di connessione',
        'es': 'Dispositivo de conexión',
        'pl': 'Urządzenie łączące',
        'zh-cn': '连接装置'
    },
    'Select VBus Connection Device Type': {
        'en': 'Select VBus Connection Device Type (VBus/LAN, DL3 etc.)',
        'de': 'Wählen Sie den VBus-Verbindungsgerätetyp (VBus/LAN, DL3 usw.).',
        'ru': 'Выберите тип устройства подключения VBus (VBus/LAN, DL3 и т. Д.)',
        'pt': 'Selecione o tipo de dispositivo de conexão VBus (VBus/LAN, DL3 etc.)',
        'nl': 'Selecteer het type VBus-verbindingsapparaat (VBus/LAN, DL3 enz.)',
        'fr': 'Sélectionnez le type de périphérique de connexion VBus (VBus/LAN, DL3, etc.)',
        'it': 'Seleziona il tipo di dispositivo di connessione VBus (VBus/LAN, DL3 ecc.)',
        'es': 'Seleccione el tipo de dispositivo de conexión VBus (VBus/LAN, DL3, etc.)',
        'pl': 'Wybierz typ urządzenia podłączeniowego VBus (VBus/LAN, DL3 itp.)',
        'zh-cn': '选择VBus连接设备类型（VBus/LAN，DL3等）'
    },
    'VBus/USB': {
        'en': 'VBus/USB',
        'de': 'VBus/USB',
        'ru': 'VBus/USB',
        'pt': 'VBus/USB',
        'nl': 'VBus/USB',
        'fr': 'VBus/USB',
        'it': 'VBus/USB',
        'es': 'VBus/USB',
        'pl': 'VBus/USB',
        'zh-cn': 'VBus/USB'
    },
    'Serial/LANGW': {
        'en': 'Serial/LANGW',
        'de': 'Seriell/LANGW',
        'ru': 'Последовательный/LANGW',
        'pt': 'Serial/LANGW',
        'nl': 'Serieel/LANGW',
        'fr': 'Série/LANGW',
        'it': 'Serial/LANGW',
        'es': 'Serie/LANGW',
        'pl': 'Szeregowy/LANGW',
        'zh-cn': '串口/LANGW'
    },
    'VBus/LAN': {
        'en': 'VBus/LAN',
        'de': 'VBus/LAN',
        'ru': 'VBus/LAN',
        'pt': 'VBus/LAN',
        'nl': 'VBus/LAN',
        'fr': 'VBus/LAN',
        'it': 'VBus/LAN',
        'es': 'VBus/LAN',
        'pl': 'VBus/LAN',
        'zh-cn': 'VBus/局域网'
    },
    'DL2/KM2': {
        'en': 'DL2 / KM2',
        'de': 'DL2 / KM2',
        'ru': 'DL2 / КМ2',
        'pt': 'DL2 / KM2',
        'nl': 'DL2 / KM2',
        'fr': 'DL2 / KM2',
        'it': 'DL2 / KM2',
        'es': 'DL2 / KM2',
        'pl': 'DL2 / KM2',
        'zh-cn': 'DL2 / KM2'
    },
    'DL3': {
        'en': 'DL3',
        'de': 'DL3',
        'ru': 'DL3',
        'pt': 'DL3',
        'nl': 'DL3',
        'fr': 'DL3',
        'it': 'DL3',
        'es': 'DL3',
        'pl': 'DL3',
        'zh-cn': 'DL3'
    },
    'Connection Identifier': {
        'en': 'Connection Identifier',
        'de': 'Verbindungskennung',
        'ru': 'Идентификатор соединения',
        'pt': 'Identificador de conexão',
        'nl': 'Verbindingsidentificatie',
        'fr': 'Identifiant de connexion',
        'it': 'Identificatore di connessione',
        'es': 'Identificador de conexión',
        'pl': 'Identyfikator połączenia',
        'zh-cn': '连接标识符'
    },
    'Connection Port': {
        'en': 'Connection Port',
        'de': 'Verbindungs-Port',
        'ru': 'Порт подключения',
        'pt': 'Porta de conexão',
        'nl': 'Verbindingspoort',
        'fr': 'Port de connexion',
        'it': 'Porta di connessione',
        'es': 'Puerto de conexión',
        'pl': 'Port połączenia',
        'zh-cn': '连接口'
    },
    'Default: 7053': {
        'en': 'Default: 7053',
        'de': 'Standard: 7053',
        'ru': 'По умолчанию: 7053',
        'pt': 'Padrão: 7053',
        'nl': 'Standaard: 7053',
        'fr': 'Par défaut: 7053',
        'it': 'Predefinito: 7053',
        'es': 'Predeterminado: 7053',
        'pl': 'Domyślnie: 7053',
        'zh-cn': '默认值：7053'
    },
    'Host address (IP or FQDN) for local LAN and for VBus.net or Serial Port Id for VBus/USB access': {
        'en': 'Host address (IP or FQDN) for local LAN and for VBus.net or Serial Port Id for VBus/USB access',
        'de': 'Hostadresse (IP oder FQDN) für lokales LAN und für VBus.net oder serielle Port-ID für VBus/USB-Zugriff',
        'ru': 'Адрес хоста (IP или FQDN) для локальной сети и для VBus.net или Id последовательного порта для доступа к VBus/USB',
        'pt': 'Endereço de host (IP ou FQDN) para LAN local e para VBus.net ou ID de porta serial para acesso VBus/USB',
        'nl': 'Hostadres (IP of FQDN) voor lokaal LAN en voor VBus.net of seriële poort-ID voor VBus/USB-toegang',
        'fr': "Adresse d'hôte (IP ou FQDN) pour le LAN local et pour VBus.net ou ID de port série pour l'accès VBus/USB",
        'it': 'Indirizzo host (IP o FQDN) per LAN locale e per VBus.net o ID porta seriale per accesso VBus/USB',
        'es': 'Dirección de host (IP o FQDN) para LAN local y para VBus.net o Id. De puerto serie para acceso VBus/USB',
        'pl': 'Adres hosta (IP lub FQDN) dla lokalnej sieci LAN i VBus.net lub identyfikator portu szeregowego dla dostępu VBus/USB',
        'zh-cn': '本地LAN和VBus.net的主机地址（IP或FQDN）或VBus/USB访问的串行端口ID'
    },
    'VBus Password': {
        'en': 'VBus Password',
        'de': 'VBus Passwort',
        'ru': 'VBus Пароль',
        'pt': 'Senha do VBus',
        'nl': 'VBus-wachtwoord',
        'fr': 'Mot de passe VBus',
        'it': 'Password VBus',
        'es': 'Contraseña de VBus',
        'pl': 'Hasło VBus',
        'zh-cn': 'VBus密码'
    },
    'Default: vbus': {
        'en': 'Default: vbus',
        'de': 'Standard: vbus',
        'ru': 'По умолчанию: vbus',
        'pt': 'Padrão: vbus',
        'nl': 'Standaard: vbus',
        'fr': 'Par défaut: vbus',
        'it': 'Predefinito: vbus',
        'es': 'Predeterminado: vbus',
        'pl': 'Domyślnie: vbus',
        'zh-cn': '默认值：vbus'
    },
    'DL3 Channel 1': {
        'en': 'DL3 Channel 1',
        'de': 'DL3-Kanal 1',
        'ru': 'DL3 канал 1',
        'pt': 'Canal DL3 1',
        'nl': 'DL3 kanaal 1',
        'fr': 'DL3 Channel 1',
        'it': 'Canale DL3 1',
        'es': 'DL3 Canal 1',
        'pl': 'Kanał DL3 1',
        'zh-cn': 'DL3频道1'
    },
    'DL3 Channel 2': {
        'en': 'DL3 Channel 2',
        'de': 'DL3-Kanal 2',
        'ru': 'DL3 канал 2',
        'pt': 'Canal DL3 2',
        'nl': 'DL3 kanaal 2',
        'fr': 'DL3 Channel 2',
        'it': 'Canale DL3 2',
        'es': 'DL3 Canal 2',
        'pl': 'Kanał DL3 2',
        'zh-cn': 'DL3频道2'
    },
    'DL3 Channel 3': {
        'en': 'DL3 Channel 3',
        'de': 'DL3-Kanal 3',
        'ru': 'DL3 канал 3',
        'pt': 'Canal DL3 3',
        'nl': 'DL3 kanaal 3',
        'fr': 'DL3 Channel 3',
        'it': 'Canale DL3 3',
        'es': 'DL3 Canal 3',
        'pl': 'Kanał DL3 3',
        'zh-cn': 'DL3频道3'
    },
    'DL3 Channel 4': {
        'en': 'DL3 Channel 4',
        'de': 'DL3-Kanal 4',
        'ru': 'DL3 канал 4',
        'pt': 'Canal DL3 4',
        'nl': 'DL3 kanaal 4',
        'fr': 'DL3 Channel 4',
        'it': 'Canale DL3 4',
        'es': 'DL3 Canal 4',
        'pl': 'Kanał DL3 4',
        'zh-cn': 'DL3频道4'
    },
    'DL3 Channel 5': {
        'en': 'DL3 Channel 5',
        'de': 'DL3-Kanal 5',
        'ru': 'DL3 канал 5',
        'pt': 'Canal DL3 5',
        'nl': 'DL3 kanaal 5',
        'fr': 'DL3 Channel 5',
        'it': 'Canale DL3 5',
        'es': 'DL3 Canal 5',
        'pl': 'Kanał DL3 5',
        'zh-cn': 'DL3频道5'
    },
    'DL3 Channel 6': {
        'en': 'DL3 Channel 6',
        'de': 'DL3-Kanal 6',
        'ru': 'DL3 канал 6',
        'pt': 'Canal DL3 6',
        'nl': 'DL3 kanaal 6',
        'fr': 'DL3 Channel 6',
        'it': 'Canale DL3 6',
        'es': 'DL3 Canal 6',
        'pl': 'Kanał DL3 6',
        'zh-cn': 'DL3频道6'
    },
    'DL3 Channel 0': {
        'en': 'DL3 Channel 0',
        'de': 'DL3-Kanal 0',
        'ru': 'DL3 канал 0',
        'pt': 'Canal DL3 0',
        'nl': 'DL3 kanaal 0',
        'fr': 'DL3 Channel 0',
        'it': 'Canale DL3 0',
        'es': 'DL3 Canal 0',
        'pl': 'Kanał DL3 0',
        'zh-cn': 'DL3频道0'
    },
    'DL3 Channel': {
        'en': 'DL3 Channel',
        'de': 'DL3-Kanal',
        'ru': 'Канал DL3',
        'pt': 'Canal DL3',
        'nl': 'DL3-kanaal',
        'fr': 'Canal DL3',
        'it': 'Canale DL3',
        'es': 'Canal DL3',
        'pl': 'Kanał DL3',
        'zh-cn': 'DL3频道'
    },
    'Required for DL3 only': {
        'en': 'Required for DL3 only',
        'de': 'Nur für DL3 erforderlich',
        'ru': 'Требуется только для DL3',
        'pt': 'Necessário apenas para DL3',
        'nl': 'Alleen vereist voor DL3',
        'fr': 'Requis pour DL3 uniquement',
        'it': 'Richiesto solo per DL3',
        'es': 'Requerido solo para DL3',
        'pl': 'Wymagane tylko dla DL3',
        'zh-cn': '仅DL3需要'
    },
    'Via tag': {
        'en': 'Via tag',
        'de': 'Via-Kennung',
        'ru': 'Через тег',
        'pt': 'Via tag',
        'nl': 'Via tag',
        'fr': 'Via tag',
        'it': 'Tramite tag',
        'es': 'Vía etiqueta',
        'pl': 'Poprzez tag',
        'zh-cn': '通过标签'
    },
    'Required only for VBus.net access via DLx/KMx': {
        'en': 'Required only for VBus.net access via DLx / KMx',
        'de': 'Nur für den VBus.net-Zugriff über DLx / KMx erforderlich',
        'ru': 'Требуется только для доступа к VBus.net через DLx / KMx',
        'pt': 'Necessário apenas para acesso ao VBus.net via DLx / KMx',
        'nl': 'Alleen vereist voor toegang tot VBus.net via DLx / KMx',
        'fr': "Requis uniquement pour l'accès à VBus.net via DLx / KMx",
        'it': "Richiesto solo per l'accesso VBus.net tramite DLx / KMx",
        'es': 'Se requiere solo para el acceso a VBus.net a través de DLx / KMx',
        'pl': 'Wymagane tylko dla dostępu VBus.net przez DLx / KMx',
        'zh-cn': '仅通过DLx / KMx访问VBus.net时才需要'
    },
    'VBus Interval': {
        'en': 'VBus Update Interval (in seconds)',
        'de': 'VBus-Aktualisierungsintervall (in Sekunden)',
        'ru': 'Интервал обновления VBus (в секундах)',
        'pt': 'Intervalo de atualização do VBus (em segundos)',
        'nl': 'VBus Update-interval (in seconden)',
        'fr': 'Intervalle de mise à jour VBus (en secondes)',
        'it': 'Intervallo di aggiornamento VBus (in secondi)',
        'es': 'Intervalo de actualización de VBus (en segundos)',
        'pl': 'Interwał aktualizacji VBus (w sekundach)',
        'zh-cn': 'VBus更新间隔（以秒为单位）'
    },
    'If Force Adapter Reinitialization is set, the adapter restarts with new configuration immediately on save': {
        'en': 'If Force Adapter Reinitialization is set, the adapter restarts with new configuration immediately on save',
        'de': 'Wenn Adapter Reinitialization gesetzt ist, wird der Adapter sofort nach dem Speichern mit einer neuen Konfiguration neu gestartet',
        'ru': 'Если установлена принудительная повторная инициализация адаптера, адаптер перезапускается с новой конфигурацией сразу после сохранения.',
        'pt': 'Se Forçar reinicialização do adaptador estiver definido, o adaptador será reiniciado com a nova configuração imediatamente ao salvar',
        'nl': 'Als Force Adapter Reinitialization is ingesteld, wordt de adapter onmiddellijk opnieuw opgestart met een nieuwe configuratie',
        'fr': "Si Forcer la réinitialisation de l'adaptateur est défini, l'adaptateur redémarre avec la nouvelle configuration immédiatement lors de l'enregistrement",
        'it': "Se si imposta Reinizializzazione forzata adattatore, l'adattatore si riavvia con una nuova configurazione immediatamente al momento del salvataggio",
        'es': 'Si se establece Forzar reinicialización del adaptador, el adaptador se reinicia con una nueva configuración inmediatamente al guardar',
        'pl': 'Jeśli ustawiona jest opcja Wymuś ponowne zainicjowanie adaptera, adapter ponownie uruchamia się z nową konfiguracją natychmiast po zapisaniu',
        'zh-cn': '如果设置了“强制适配器重新初始化”，则适配器在保存时立即以新配置重新启动'
    },
    'Force Adapter Reinitialization': {
        'en': 'Force Adapter Reinitialization',
        'de': 'Reinitialisierung des Adapters erzwingen',
        'ru': 'Реинициализация силового адаптера',
        'pt': 'Forçar reinicialização do adaptador',
        'nl': 'Forceer opnieuw initialiseren van adapter',
        'fr': "Forcer la réinitialisation de l'adaptateur",
        'it': "Reinizializzazione dell'adattatore di forza",
        'es': 'Reinicialización del adaptador de fuerza',
        'pl': 'Wymuś ponowne zainicjowanie adaptera',
        'zh-cn': '强制适配器重新初始化'
    }
};