/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Celsius": {                                     "en": "Celsius",                                         "de": "Celsius",                                         "ru": "Цельсия",                                         "pt": "Celsius",                                         "nl": "Celsius",                                         "fr": "Celsius",                                         "it": "Centigrado",                                      "es": "Celsius",                                         "pl": "Celsjusz",                                        "zh-cn": "摄氏温度"},
    "Fahrenheit": {                                  "en": "Fahrenheit",                                      "de": "Fahrenheit",                                      "ru": "Фаренгейт",                                       "pt": "Fahrenheit",                                      "nl": "Fahrenheit",                                      "fr": "Fahrenheit",                                      "it": "Fahrenheit",                                      "es": "Fahrenheit",                                      "pl": "Fahrenheit",                                      "zh-cn": "华氏温度"},
    "Kelvin": {                                      "en": "Kelvin",                                          "de": "Kelvin",                                          "ru": "Кельвин",                                         "pt": "Kelvin",                                          "nl": "Kelvin",                                          "fr": "Kelvin",                                          "it": "Kelvin",                                          "es": "Kelvin",                                          "pl": "kelwin",                                          "zh-cn": "开尔文"},
    "Lbl_Password": {                                "en": "Password",                                        "de": "Passwort",                                        "ru": "пароль",                                          "pt": "Senha",                                           "nl": "Wachtwoord",                                      "fr": "Mot de passe",                                    "it": "Parola d'ordine",                                 "es": "Contraseña",                                      "pl": "Hasło",                                           "zh-cn": "密码"},
    "Lbl_country": {                                 "en": "Countrycode",                                     "de": "Ländercode",                                      "ru": "Код страны",                                      "pt": "Código do país",                                  "nl": "Landcode",                                        "fr": "Code postal",                                     "it": "Prefisso internazionale",                         "es": "Código de país",                                  "pl": "Kod pocztowy",                                    "zh-cn": "国家代码"},
    "Lbl_email": {                                   "en": "eMail",                                           "de": "Email",                                           "ru": "Эл. адрес",                                       "pt": "o email",                                         "nl": "e-mail",                                          "fr": "email",                                           "it": "e-mail",                                          "es": "correo electrónico",                              "pl": "e-mail",                                          "zh-cn": "电子邮件"},
    "Lbl_temperatureUnit": {                         "en": "Temperature unit",                                "de": "Temperatureinheit",                               "ru": "Единица измерения температуры",                   "pt": "Unidade de temperatura",                          "nl": "Temperatuureenheid",                              "fr": "Unité de température",                            "it": "Unità di temperatura",                            "es": "Unidad de temperatura",                           "pl": "Jednostka temperatury",                           "zh-cn": "温度单位"},
    "Poll_Interval": {                               "en": "Pollinterval",                                    "de": "Pollinterval",                                    "ru": "Период опыления",                                 "pt": "Pollinterval",                                    "nl": "Pollinterval",                                    "fr": "Intervalle de sondage",                           "it": "Pollinterval",                                    "es": "Intervalo de encuesta",                           "pl": "Pollinterval",                                    "zh-cn": "轮询间隔"},
    "Poll_Interval_desc": {                          "en": "Request new status and sensor information from devices every X seconds.", "de": "Fordern Sie alle X Sekunden neue Status- und Sensorinformationen von den Geräten an.", "ru": "Запрашивать новое состояние и информацию о датчиках от устройств каждые X секунд.", "pt": "Solicite novos status e informações do sensor dos dispositivos a cada X segundos.", "nl": "Vraag elke X seconden nieuwe status- en sensorinformatie van apparaten op.", "fr": "Demandez de nouveaux états et informations sur les capteurs aux appareils toutes les X secondes.", "it": "Richiedi nuove informazioni sullo stato e sui sensori dai dispositivi ogni X secondi.", "es": "Solicite nueva información de estado y sensor de los dispositivos cada X segundos.", "pl": "Żądaj nowego statusu i informacji z czujników z urządzeń co X sekund.", "zh-cn": "每隔X秒从设备请求新的状态和传感器信息。"},
    "austria": {                                     "en": "Austria",                                         "de": "Österreich",                                      "ru": "Австрия",                                         "pt": "Áustria",                                         "nl": "Oostenrijk",                                      "fr": "L'Autriche",                                      "it": "Austria",                                         "es": "Austria",                                         "pl": "Austria",                                         "zh-cn": "奥地利"},
    "country_desc": {                                "en": "ISO-Code of the country you created your dyson Account in.", "de": "ISO-Code des Landes, in dem Sie Ihr Dyson-Konto erstellt haben.", "ru": "ISO-код страны, в которой вы создали свою учетную запись dyson.", "pt": "Código ISO do país em que criou a sua conta dyson.", "nl": "ISO-code van het land waarin je je dyson-account hebt aangemaakt.", "fr": "Code ISO du pays dans lequel vous avez créé votre compte dyson.", "it": "Codice ISO del paese in cui hai creato il tuo account dyson.", "es": "Código ISO del país en el que creó su cuenta Dyson.", "pl": "Kod ISO kraju, w którym utworzyłeś swoje konto Dyson.", "zh-cn": "您创建戴森帐户所在国家/地区的ISO代码。"},
    "email_desc": {                                  "en": "email address of your dyson account.",            "de": "E-Mail-Adresse Ihres Dyson-Kontos.",              "ru": "адрес электронной почты вашей учетной записи dyson.", "pt": "endereço de e-mail da sua conta dyson.",          "nl": "e-mailadres van uw dyson-account.",               "fr": "l'adresse e-mail de votre compte dyson.",         "it": "indirizzo e-mail del tuo account dyson.",         "es": "dirección de correo electrónico de su cuenta de dyson.", "pl": "adres e-mail twojego konta dyson.",               "zh-cn": "您的戴森帐户的电子邮件地址。"},
    "germany": {                                     "en": "Germany",                                         "de": "Deutschland",                                     "ru": "Германия",                                        "pt": "Alemanha",                                        "nl": "Duitsland",                                       "fr": "Allemagne",                                       "it": "Germania",                                        "es": "Alemania",                                        "pl": "Niemcy",                                          "zh-cn": "德国"},
    "france": {                                      "en": "France",                                          "de": "Frankreich",                                      "ru": "Франция",                                         "pt": "França",                                          "nl": "Frankrijk",                                       "fr": "France",                                          "it": "Francia",                                         "es": "Francia",                                         "pl": "Francja",                                         "zh-cn": "法国"},
    "password_desc": {                               "en": "Password of your dyson account.",                 "de": "Passwort Ihres Dyson-Kontos.",                    "ru": "Пароль вашей учетной записи dyson.",              "pt": "Senha da sua conta dyson.",                       "nl": "Wachtwoord van uw dyson-account.",                "fr": "Mot de passe de votre compte dyson.",             "it": "Password del tuo account dyson.",                 "es": "Contraseña de su cuenta de dyson.",               "pl": "Hasło Twojego konta Dyson.",                      "zh-cn": "dyson帐户的密码。"},
    "temperatureUnit_desc": {                        "en": "Unit to display the temperature.",                "de": "Einheit zur Anzeige der Temperatur.",             "ru": "Единица для отображения температуры.",            "pt": "Unidade para exibir a temperatura.",              "nl": "Eenheid om de temperatuur weer te geven.",        "fr": "Unité pour afficher la température.",             "it": "Unità per visualizzare la temperatura.",          "es": "Unidad para mostrar la temperatura.",             "pl": "Jednostka do wyświetlania temperatury.",          "zh-cn": "显示温度的单位。"},
};