/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Celsius": {                                     "en": "Celsius",                                         "de": "Celsius",                                         "ru": "Цельсия",                                         "pt": "Celsius",                                         "nl": "Celsius",                                         "fr": "Celsius",                                         "it": "Centigrado",                                      "es": "Celsius",                                         "pl": "Celsjusz",                                        "zh-cn": "摄氏温度"},
    "Fahrenheit": {                                  "en": "Fahrenheit",                                      "de": "Fahrenheit",                                      "ru": "Фаренгейт",                                       "pt": "Fahrenheit",                                      "nl": "Fahrenheit",                                      "fr": "Fahrenheit",                                      "it": "Fahrenheit",                                      "es": "Fahrenheit",                                      "pl": "Fahrenheit",                                      "zh-cn": "华氏温度"},
    "Kelvin": {                                      "en": "Kelvin",                                          "de": "Kelvin",                                          "ru": "Кельвин",                                         "pt": "Kelvin",                                          "nl": "Kelvin",                                          "fr": "Kelvin",                                          "it": "Kelvin",                                          "es": "Kelvin",                                          "pl": "kelwin",                                          "zh-cn": "开尔文"},
    "Lbl_Password": {                                "en": "password",                                        "de": "Passwort",                                        "ru": "пароль",                                          "pt": "senha",                                           "nl": "wachtwoord",                                      "fr": "mot de passe",                                    "it": "parola d'ordine",                                 "es": "contraseña",                                      "pl": "hasło",                                           "zh-cn": "密码"},
    "Lbl_country": {                                 "en": "Countrycode",                                     "de": "Ländercode",                                      "ru": "Код страны",                                      "pt": "Código do país",                                  "nl": "Landcode",                                        "fr": "Code postal",                                     "it": "Prefisso internazionale",                         "es": "Código de país",                                  "pl": "Kod pocztowy",                                    "zh-cn": "国家代码"},
    "Lbl_email": {                                   "en": "eMail",                                           "de": "Email",                                           "ru": "Эл. адрес",                                       "pt": "o email",                                         "nl": "e-mail",                                          "fr": "email",                                           "it": "e-mail",                                          "es": "correo electrónico",                              "pl": "e-mail",                                          "zh-cn": "电子邮件"},
    "Lbl_temperatureUnit": {                         "en": "Temperature unit",                                "de": "Temperatureinheit",                               "ru": "Единица измерения температуры",                   "pt": "Unidade de temperatura",                          "nl": "Temperatuureenheid",                              "fr": "Unité de température",                            "it": "Unità di temperatura",                            "es": "Unidad de temperatura",                           "pl": "Jednostka temperatury",                           "zh-cn": "温度单位"},
    "Poll_Interval": {                               "en": "Pollinterval",                                    "de": "Pollinterval",                                    "ru": "Период опыления",                                 "pt": "Pollinterval",                                    "nl": "Pollinterval",                                    "fr": "Intervalle de sondage",                           "it": "Pollinterval",                                    "es": "Intervalo de encuesta",                           "pl": "Pollinterval",                                    "zh-cn": "轮询间隔"},
    "Poll_Interval_desc": {                          "en": "Look for new devices every x minutes.",           "de": "Suchen Sie alle x Minuten nach neuen Geräten.",   "ru": "Ищите новые устройства каждые x минут.",          "pt": "Procure novos dispositivos a cada x minutos.",    "nl": "Zoek elke x minuten naar nieuwe apparaten.",      "fr": "Recherchez de nouveaux appareils toutes les x minutes.", "it": "Cerca nuovi dispositivi ogni x minuti.",          "es": "Busque nuevos dispositivos cada x minutos.",      "pl": "Szukaj nowych urządzeń co x minut.",              "zh-cn": "每隔x分钟寻找新设备。"},
    "country_desc": {                                "en": "ISO-Code of the country you created your dyson Account in.", "de": "ISO-Code des Landes, in dem Sie Ihr Dyson-Konto erstellt haben.", "ru": "ISO-код страны, в которой вы создали свою учетную запись dyson.", "pt": "Código ISO do país em que criou a sua conta dyson.", "nl": "ISO-code van het land waarin je je dyson-account hebt aangemaakt.", "fr": "Code ISO du pays dans lequel vous avez créé votre compte dyson.", "it": "Codice ISO del paese in cui hai creato il tuo account dyson.", "es": "Código ISO del país en el que creó su cuenta Dyson.", "pl": "Kod ISO kraju, w którym utworzyłeś swoje konto Dyson.", "zh-cn": "您创建戴森帐户所在国家/地区的ISO代码。"},
    "email_desc": {                                  "en": "email address of your dyson account.",            "de": "E-Mail-Adresse Ihres Dyson-Kontos.",              "ru": "адрес электронной почты вашей учетной записи dyson.", "pt": "endereço de e-mail da sua conta dyson.",          "nl": "e-mailadres van uw dyson-account.",               "fr": "l'adresse e-mail de votre compte dyson.",         "it": "indirizzo e-mail del tuo account dyson.",         "es": "dirección de correo electrónico de su cuenta de dyson.", "pl": "adres e-mail twojego konta dyson.",               "zh-cn": "您的戴森帐户的电子邮件地址。"},
    "germany": {                                     "en": "Germany",                                         "de": "Deutschland",                                     "ru": "Германия",                                        "pt": "Alemanha",                                        "nl": "Duitsland",                                       "fr": "Allemagne",                                       "it": "Germania",                                        "es": "Alemania",                                        "pl": "Niemcy",                                          "zh-cn": "德国"},
    "password_desc": {                               "en": "Password of your dyson account.",                 "de": "Passwort Ihres Dyson-Kontos.",                    "ru": "Пароль вашей учетной записи dyson.",              "pt": "Senha da sua conta dyson.",                       "nl": "Wachtwoord van uw dyson-account.",                "fr": "Mot de passe de votre compte dyson.",             "it": "Password del tuo account dyson.",                 "es": "Contraseña de su cuenta de dyson.",               "pl": "Hasło Twojego konta Dyson.",                      "zh-cn": "dyson帐户的密码。"},
    "temperatureUnit_desc": {                        "en": "Unit the temperature will be shown in.",          "de": "In der Einheit wird die Temperatur in angezeigt.", "ru": "В единицах измерения будет отображаться температура.", "pt": "Unidade em que a temperatura será mostrada.",     "nl": "Eenheid waarin de temperatuur wordt weergegeven.", "fr": "Unité dans laquelle la température sera affichée.", "it": "Unità in cui verrà mostrata la temperatura.",     "es": "Unidad en la que se mostrará la temperatura.",    "pl": "Jednostka, w której będzie wyświetlana temperatura.", "zh-cn": "将显示温度单位。"},
};